export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/db';
import fs from 'fs';
import path from 'path';

export async function GET(req: NextRequest) {
  const scanId = req.nextUrl.searchParams.get('scanId');
  const format = req.nextUrl.searchParams.get('format') || 'md';

  if (!scanId) {
    return NextResponse.json({ error: 'scanId required' }, { status: 400 });
  }

  const scan = getDb().prepare('SELECT * FROM security_scans WHERE id = ?').get(Number(scanId)) as any;
  if (!scan) {
    return NextResponse.json({ error: 'Scan not found' }, { status: 404 });
  }

  const report = scan.report || 'No report available.';
  const platformSlug = scan.platform_name.toLowerCase().replace(/\s+/g, '-');
  const dateStr = scan.created_at ? new Date(scan.created_at + 'Z').toISOString().split('T')[0] : 'unknown';

  if (format === 'html') {
    // Generate a styled HTML version for printing to PDF via browser
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${scan.platform_name} — Security Audit Report</title>
  <style>
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.6; }
    h1 { color: #0d0d0d; border-bottom: 3px solid #333; padding-bottom: 10px; font-size: 24px; }
    h2 { color: #1a1a1a; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-top: 30px; font-size: 18px; }
    h3 { color: #333; margin-top: 20px; font-size: 15px; }
    h4 { color: #555; font-size: 13px; }
    pre, code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 12px; }
    pre { padding: 12px; overflow-x: auto; white-space: pre-wrap; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 13px; }
    th { background: #f0f0f0; font-weight: 600; }
    .meta { color: #666; font-size: 13px; margin-bottom: 20px; }
    .finding { border-left: 3px solid #ddd; padding-left: 12px; margin: 10px 0; }
    .critical { border-left-color: #dc2626; }
    .warning { border-left-color: #f59e0b; }
    .info { border-left-color: #3b82f6; }
    @page { margin: 20mm; }
  </style>
</head>
<body>
  <div class="meta">
    Platform: ${scan.platform_name} · Model: ${scan.model} · Date: ${dateStr} · Duration: ${scan.duration_seconds ? Math.round(scan.duration_seconds / 60) + ' min' : 'N/A'} · Cost: $${(scan.estimated_cost || 0).toFixed(2)}
  </div>
  ${markdownToHtml(report)}
  <hr>
  <p style="color: #999; font-size: 11px;">Generated by Claude Security Scanner · ${new Date().toISOString()}</p>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="${platformSlug}-security-report-${dateStr}.html"`,
      },
    });
  }

  // Default: Markdown download
  return new NextResponse(report, {
    headers: {
      'Content-Type': 'text/markdown',
      'Content-Disposition': `attachment; filename="${platformSlug}-security-report-${dateStr}.md"`,
    },
  });
}

/** Simple Markdown → HTML converter (no external deps) */
function markdownToHtml(md: string): string {
  let html = md
    // Escape HTML
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    // Headers
    .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold & italic
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Checkboxes
    .replace(/^- \[ \] (.+)$/gm, '<div>☐ $1</div>')
    .replace(/^- \[x\] (.+)$/gm, '<div>☑ $1</div>')
    // Unordered lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Tables (basic)
    .replace(/^\|(.+)\|$/gm, (match) => {
      const cells = match.split('|').filter(c => c.trim()).map(c => c.trim());
      if (cells.every(c => c.match(/^[-:]+$/))) return ''; // separator row
      const tag = 'td';
      return '<tr>' + cells.map(c => `<${tag}>${c}</${tag}>`).join('') + '</tr>';
    })
    // Paragraphs (double newline)
    .replace(/\n\n/g, '</p><p>')
    // Single newlines
    .replace(/\n/g, '<br>');

  // Wrap loose <li> in <ul>
  html = html.replace(/(<li>[\s\S]*?<\/li>)+/g, '<ul>$&</ul>');
  // Wrap loose <tr> in <table>
  html = html.replace(/(<tr>[\s\S]*?<\/tr>)+/g, '<table>$&</table>');

  return `<p>${html}</p>`;
}
